none: []

knowledge_author:
  - create_knowledge_base
  - list_knowledge_bases
  - create_category
  - list_categories
  - create_article
  - update_article
  - publish_article
  - list_articles
  - get_article

table_explorer:
  - list_tables
  - get_table
  - list_records
  - get_record

topic_extractor:
  - extract_topic

full:
  - create_knowledge_base
  - list_knowledge_bases
  - create_category
  - list_categories
  - create_article
  - update_article
  - publish_article
  - list_articles
  - get_article
  - list_tables
  - get_table
  - list_records
  - get_record
  - extract_topic
